= Externalized Configuration - Eclipse Vert.x Booster

IMPORTANT: While you can run and interact with this booster on our local host, you cannot take advantage of using ConfigMap with this booster without using OpenShift. For more details on using this booster with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/vertx-runtime.html[Eclipse Vert.x Runtime Guide].

IMPORTANT: This booster requires Java 8 or greater and Maven 3.3.x or greater.

IMPORTANT: As part of the process of creating this booster, launch.openshift.io set up a project with a CI/CD deployment of this booster. You can see the status of this deployment in your Single-node OpenShift Cluster or OpenShift Online Web Console. 

== Running the Booster Locally
To run this booster on your local host:

[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:${loggedUser}/myvertxconfig

$ cd myvertxconfig

$ mvn compile vertx:run
----

== Interacting with the Booster Locally
To interact with your booster while its running, use the form at `http://localhost:8080` or the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/greeting
{"content":"Hello, World!"}

$ curl http://localhost:8080/api/greeting?name=Sarah
{"content":"Hello, Sarah!"}
----

== Running the Booster on a OpenShift Cluster
If you have a OpenShift cluster, such as CDK or the Red Hat Developer Sandbox, link:https://developers.redhat.com/developer-sandbox[Welcome to the Developer Sandbox for Red Hat OpenShift]. 
This example uses now a new created ServiceAccount (myvertxconfig-sa). 
This SA has a rolebinding(myvertxconfig-bind) to the role(myvertxconfig-role).
This role enables only access to the configmaps in the same namespace.

To deploy your booster to a running single-node OpenShift cluster:

. Log in and create your project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME
----

. Navigate to the root directory of your booster.

. Deploy your ConfigMap configuration using `app-config.yml`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create configmap app-config --from-file=app-config.yml
----

. Deploy your booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----

. Undeploy your booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn fabric8:undeploy -Popenshift
$ oc delete bc myvertxconfig-s2i
$ oc delete is myvertxconfig
----

== Interacting with the Booster on a Single-node OpenShift Cluster

To interact with your booster while it's running on a Single-node OpenShift Cluster, you first need to obtain it's URL:

[source,bash,options="nowrap",subs="attributes+"]
----
$ export URL=`oc get route myvertxconfig -o jsonpath={$.spec.host}`
$ echo $URL

myvertxconfig-MY_PROJECT_NAME.OPENSHIFT_HOSTNAME
----


You can use the form at your application's url or you can use the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl $URL/api/greeting
{"content":"Hello World from a ConfigMap!"}

$ curl $URL/api/greeting?name=Sarah
{"content":"Hello Sarah from a ConfigMap!"}
----

== More Information
You can learn more about this booster and rest of the Eclipse Vert.x runtime in the link: https://appdev.openshift.io/docs/vertx-runtime.html[Eclipse Vert.x Runtime Guide].
