spec:
  replicas: 1
  template:
    spec:
      containers:
        - resources:
            limits:
              memory: '100Mi'
          env:
            - name: JAVA_OPTIONS
      serviceAccount: myvertxconfig-sa
