apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myvertxconfig-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch"]