kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myvertxconfig-binding
subjects:
  - kind: ServiceAccount
    name: myvertxconfig-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myvertxconfig-role
